# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Koos/Desktop/JULIAN BESTANDEN VOOR OP VAKANTIE/shove/client/assets/shove.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 724)
        MainWindow.setMinimumSize(QtCore.QSize(1112, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("window_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.MainWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabwMain = QtWidgets.QTabWidget(self.MainWidget)
        self.tabwMain.setObjectName("tabwMain")
        self.tabGame = QtWidgets.QWidget()
        self.tabGame.setObjectName("tabGame")
        self.frameGame = QtWidgets.QFrame(self.tabGame)
        self.frameGame.setGeometry(QtCore.QRect(1, 1, 1085, 531))
        self.frameGame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGame.setObjectName("frameGame")
        self.lblGs9c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs9c1.setGeometry(QtCore.QRect(60, 90, 60, 84))
        self.lblGs9c1.setText("")
        self.lblGs9c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/Td.png"))
        self.lblGs9c1.setScaledContents(True)
        self.lblGs9c1.setObjectName("lblGs9c1")
        self.lblGs1c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs1c2.setGeometry(QtCore.QRect(501, 10, 60, 84))
        self.lblGs1c2.setText("")
        self.lblGs1c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/Jc.png"))
        self.lblGs1c2.setScaledContents(True)
        self.lblGs1c2.setObjectName("lblGs1c2")
        self.lblGs6c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs6c1.setGeometry(QtCore.QRect(510, 430, 60, 84))
        self.lblGs6c1.setText("")
        self.lblGs6c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs6c1.setScaledContents(True)
        self.lblGs6c1.setObjectName("lblGs6c1")
        self.lblGtable = QtWidgets.QLabel(self.frameGame)
        self.lblGtable.setGeometry(QtCore.QRect(41, 41, 1005, 451))
        self.lblGtable.setText("")
        self.lblGtable.setPixmap(QtGui.QPixmap("../default_user_files/table.png"))
        self.lblGtable.setScaledContents(True)
        self.lblGtable.setObjectName("lblGtable")
        self.lblGs6c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs6c2.setGeometry(QtCore.QRect(550, 430, 60, 84))
        self.lblGs6c2.setText("")
        self.lblGs6c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs6c2.setScaledContents(True)
        self.lblGs6c2.setObjectName("lblGs6c2")
        self.lblGs2c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs2c1.setGeometry(QtCore.QRect(720, 30, 60, 84))
        self.lblGs2c1.setText("")
        self.lblGs2c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs2c1.setScaledContents(True)
        self.lblGs2c1.setObjectName("lblGs2c1")
        self.lblGs8c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs8c1.setGeometry(QtCore.QRect(60, 350, 60, 84))
        self.lblGs8c1.setText("")
        self.lblGs8c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs8c1.setScaledContents(True)
        self.lblGs8c1.setObjectName("lblGs8c1")
        self.lblGs7c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs7c1.setGeometry(QtCore.QRect(290, 430, 60, 84))
        self.lblGs7c1.setText("")
        self.lblGs7c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs7c1.setScaledContents(True)
        self.lblGs7c1.setObjectName("lblGs7c1")
        self.lblGs4c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs4c2.setGeometry(QtCore.QRect(950, 360, 60, 84))
        self.lblGs4c2.setText("")
        self.lblGs4c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs4c2.setScaledContents(True)
        self.lblGs4c2.setObjectName("lblGs4c2")
        self.lblGs10c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs10c1.setGeometry(QtCore.QRect(260, 30, 60, 84))
        self.lblGs10c1.setText("")
        self.lblGs10c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/7d.png"))
        self.lblGs10c1.setScaledContents(True)
        self.lblGs10c1.setObjectName("lblGs10c1")
        self.lblGs9c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs9c2.setGeometry(QtCore.QRect(100, 90, 60, 84))
        self.lblGs9c2.setText("")
        self.lblGs9c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/3d.png"))
        self.lblGs9c2.setScaledContents(True)
        self.lblGs9c2.setObjectName("lblGs9c2")
        self.lblGs10c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs10c2.setGeometry(QtCore.QRect(300, 30, 60, 84))
        self.lblGs10c2.setText("")
        self.lblGs10c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/2c.png"))
        self.lblGs10c2.setScaledContents(True)
        self.lblGs10c2.setObjectName("lblGs10c2")
        self.lblGs7c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs7c2.setGeometry(QtCore.QRect(330, 430, 60, 84))
        self.lblGs7c2.setText("")
        self.lblGs7c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs7c2.setScaledContents(True)
        self.lblGs7c2.setObjectName("lblGs7c2")
        self.lblGs1c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs1c1.setGeometry(QtCore.QRect(461, 10, 60, 84))
        self.lblGs1c1.setText("")
        self.lblGs1c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/2d.png"))
        self.lblGs1c1.setScaledContents(True)
        self.lblGs1c1.setObjectName("lblGs1c1")
        self.lblGs3c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs3c2.setGeometry(QtCore.QRect(940, 100, 60, 84))
        self.lblGs3c2.setText("")
        self.lblGs3c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs3c2.setScaledContents(True)
        self.lblGs3c2.setObjectName("lblGs3c2")
        self.lblGs8c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs8c2.setGeometry(QtCore.QRect(100, 350, 60, 84))
        self.lblGs8c2.setText("")
        self.lblGs8c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs8c2.setScaledContents(True)
        self.lblGs8c2.setObjectName("lblGs8c2")
        self.lblGs4c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs4c1.setGeometry(QtCore.QRect(910, 360, 60, 84))
        self.lblGs4c1.setText("")
        self.lblGs4c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs4c1.setScaledContents(True)
        self.lblGs4c1.setObjectName("lblGs4c1")
        self.lblGs5c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs5c1.setGeometry(QtCore.QRect(720, 430, 60, 84))
        self.lblGs5c1.setText("")
        self.lblGs5c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs5c1.setScaledContents(True)
        self.lblGs5c1.setObjectName("lblGs5c1")
        self.lblGs5c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs5c2.setGeometry(QtCore.QRect(760, 430, 60, 84))
        self.lblGs5c2.setText("")
        self.lblGs5c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs5c2.setScaledContents(True)
        self.lblGs5c2.setObjectName("lblGs5c2")
        self.lblGs2c2 = QtWidgets.QLabel(self.frameGame)
        self.lblGs2c2.setGeometry(QtCore.QRect(760, 30, 60, 84))
        self.lblGs2c2.setText("")
        self.lblGs2c2.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs2c2.setScaledContents(True)
        self.lblGs2c2.setObjectName("lblGs2c2")
        self.lblGs3c1 = QtWidgets.QLabel(self.frameGame)
        self.lblGs3c1.setGeometry(QtCore.QRect(900, 100, 60, 84))
        self.lblGs3c1.setText("")
        self.lblGs3c1.setPixmap(QtGui.QPixmap("../default_user_files/deck/back.png"))
        self.lblGs3c1.setScaledContents(True)
        self.lblGs3c1.setObjectName("lblGs3c1")
        self.lblGbg = QtWidgets.QLabel(self.frameGame)
        self.lblGbg.setGeometry(QtCore.QRect(1, 1, 1085, 531))
        self.lblGbg.setText("")
        self.lblGbg.setPixmap(QtGui.QPixmap("../default_user_files/background.png"))
        self.lblGbg.setScaledContents(True)
        self.lblGbg.setObjectName("lblGbg")
        self.lblGpotsize = QtWidgets.QLabel(self.frameGame)
        self.lblGpotsize.setGeometry(QtCore.QRect(483, 200, 120, 16))
        self.lblGpotsize.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGpotsize.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGpotsize.setObjectName("lblGpotsize")
        self.lblGc1 = QtWidgets.QLabel(self.frameGame)
        self.lblGc1.setGeometry(QtCore.QRect(377, 224, 60, 84))
        self.lblGc1.setText("")
        self.lblGc1.setPixmap(QtGui.QPixmap("../default_user_files/deck/4c.png"))
        self.lblGc1.setScaledContents(True)
        self.lblGc1.setObjectName("lblGc1")
        self.lblGc2 = QtWidgets.QLabel(self.frameGame)
        self.lblGc2.setGeometry(QtCore.QRect(445, 224, 60, 84))
        self.lblGc2.setText("")
        self.lblGc2.setPixmap(QtGui.QPixmap("../default_user_files/deck/6c.png"))
        self.lblGc2.setScaledContents(True)
        self.lblGc2.setObjectName("lblGc2")
        self.lblGc3 = QtWidgets.QLabel(self.frameGame)
        self.lblGc3.setGeometry(QtCore.QRect(513, 224, 60, 84))
        self.lblGc3.setText("")
        self.lblGc3.setPixmap(QtGui.QPixmap("../default_user_files/deck/8s.png"))
        self.lblGc3.setScaledContents(True)
        self.lblGc3.setObjectName("lblGc3")
        self.lblGc4 = QtWidgets.QLabel(self.frameGame)
        self.lblGc4.setGeometry(QtCore.QRect(581, 224, 60, 84))
        self.lblGc4.setText("")
        self.lblGc4.setPixmap(QtGui.QPixmap("../default_user_files/deck/9d.png"))
        self.lblGc4.setScaledContents(True)
        self.lblGc4.setObjectName("lblGc4")
        self.lblGc5 = QtWidgets.QLabel(self.frameGame)
        self.lblGc5.setGeometry(QtCore.QRect(649, 224, 60, 84))
        self.lblGc5.setText("")
        self.lblGc5.setPixmap(QtGui.QPixmap("../default_user_files/deck/5d.png"))
        self.lblGc5.setScaledContents(True)
        self.lblGc5.setObjectName("lblGc5")
        self.lblGs1a = QtWidgets.QLabel(self.frameGame)
        self.lblGs1a.setGeometry(QtCore.QRect(561, 10, 64, 64))
        self.lblGs1a.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblGs1a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblGs1a.setLineWidth(3)
        self.lblGs1a.setText("")
        self.lblGs1a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs1a.setScaledContents(True)
        self.lblGs1a.setObjectName("lblGs1a")
        self.lblGs1b = QtWidgets.QLabel(self.frameGame)
        self.lblGs1b.setGeometry(QtCore.QRect(493, 134, 100, 16))
        self.lblGs1b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs1b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs1b.setObjectName("lblGs1b")
        self.lblGs2b = QtWidgets.QLabel(self.frameGame)
        self.lblGs2b.setGeometry(QtCore.QRect(760, 130, 100, 16))
        self.lblGs2b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs2b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs2b.setObjectName("lblGs2b")
        self.lblGs3b = QtWidgets.QLabel(self.frameGame)
        self.lblGs3b.setGeometry(QtCore.QRect(850, 200, 100, 16))
        self.lblGs3b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs3b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs3b.setObjectName("lblGs3b")
        self.lblGs4b = QtWidgets.QLabel(self.frameGame)
        self.lblGs4b.setGeometry(QtCore.QRect(860, 330, 100, 16))
        self.lblGs4b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs4b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs4b.setObjectName("lblGs4b")
        self.lblGs5b = QtWidgets.QLabel(self.frameGame)
        self.lblGs5b.setGeometry(QtCore.QRect(740, 390, 100, 16))
        self.lblGs5b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs5b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs5b.setObjectName("lblGs5b")
        self.lblGs6b = QtWidgets.QLabel(self.frameGame)
        self.lblGs6b.setGeometry(QtCore.QRect(540, 400, 100, 16))
        self.lblGs6b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs6b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs6b.setObjectName("lblGs6b")
        self.lblGs7b = QtWidgets.QLabel(self.frameGame)
        self.lblGs7b.setGeometry(QtCore.QRect(330, 400, 100, 16))
        self.lblGs7b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs7b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs7b.setObjectName("lblGs7b")
        self.lblGs8b = QtWidgets.QLabel(self.frameGame)
        self.lblGs8b.setGeometry(QtCore.QRect(170, 320, 100, 16))
        self.lblGs8b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs8b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs8b.setObjectName("lblGs8b")
        self.lblGs9b = QtWidgets.QLabel(self.frameGame)
        self.lblGs9b.setGeometry(QtCore.QRect(170, 180, 100, 16))
        self.lblGs9b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs9b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs9b.setObjectName("lblGs9b")
        self.lblGs10b = QtWidgets.QLabel(self.frameGame)
        self.lblGs10b.setGeometry(QtCore.QRect(300, 120, 100, 16))
        self.lblGs10b.setStyleSheet("color: rgb(255, 255, 0); font: 10pt;")
        self.lblGs10b.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGs10b.setObjectName("lblGs10b")
        self.lblGdealer = QtWidgets.QLabel(self.frameGame)
        self.lblGdealer.setGeometry(QtCore.QRect(570, 60, 48, 48))
        self.lblGdealer.setPixmap(QtGui.QPixmap("../../client/assets/dealer_button.png"))
        self.lblGdealer.setScaledContents(True)
        self.lblGdealer.setObjectName("lblGdealer")
        self.lblGs2a = QtWidgets.QLabel(self.frameGame)
        self.lblGs2a.setGeometry(QtCore.QRect(820, 30, 64, 64))
        self.lblGs2a.setText("")
        self.lblGs2a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs2a.setScaledContents(True)
        self.lblGs2a.setObjectName("lblGs2a")
        self.lblGs3a = QtWidgets.QLabel(self.frameGame)
        self.lblGs3a.setGeometry(QtCore.QRect(1000, 100, 64, 64))
        self.lblGs3a.setText("")
        self.lblGs3a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs3a.setScaledContents(True)
        self.lblGs3a.setObjectName("lblGs3a")
        self.lblGs4a = QtWidgets.QLabel(self.frameGame)
        self.lblGs4a.setGeometry(QtCore.QRect(1010, 360, 64, 64))
        self.lblGs4a.setText("")
        self.lblGs4a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs4a.setScaledContents(True)
        self.lblGs4a.setObjectName("lblGs4a")
        self.lblGs5a = QtWidgets.QLabel(self.frameGame)
        self.lblGs5a.setGeometry(QtCore.QRect(820, 430, 64, 64))
        self.lblGs5a.setText("")
        self.lblGs5a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs5a.setScaledContents(True)
        self.lblGs5a.setObjectName("lblGs5a")
        self.lblGs6a = QtWidgets.QLabel(self.frameGame)
        self.lblGs6a.setGeometry(QtCore.QRect(610, 430, 64, 64))
        self.lblGs6a.setText("")
        self.lblGs6a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs6a.setScaledContents(True)
        self.lblGs6a.setObjectName("lblGs6a")
        self.lblGs7a = QtWidgets.QLabel(self.frameGame)
        self.lblGs7a.setGeometry(QtCore.QRect(390, 430, 64, 64))
        self.lblGs7a.setText("")
        self.lblGs7a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs7a.setScaledContents(True)
        self.lblGs7a.setObjectName("lblGs7a")
        self.lblGs8a = QtWidgets.QLabel(self.frameGame)
        self.lblGs8a.setGeometry(QtCore.QRect(160, 350, 64, 64))
        self.lblGs8a.setText("")
        self.lblGs8a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs8a.setScaledContents(True)
        self.lblGs8a.setObjectName("lblGs8a")
        self.lblGs9a = QtWidgets.QLabel(self.frameGame)
        self.lblGs9a.setGeometry(QtCore.QRect(160, 90, 64, 64))
        self.lblGs9a.setText("")
        self.lblGs9a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs9a.setScaledContents(True)
        self.lblGs9a.setObjectName("lblGs9a")
        self.lblGs10a = QtWidgets.QLabel(self.frameGame)
        self.lblGs10a.setGeometry(QtCore.QRect(360, 30, 64, 64))
        self.lblGs10a.setText("")
        self.lblGs10a.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.lblGs10a.setScaledContents(True)
        self.lblGs10a.setObjectName("lblGs10a")
        self.lblGbg.raise_()
        self.lblGtable.raise_()
        self.lblGs9c1.raise_()
        self.lblGs6c1.raise_()
        self.lblGs6c2.raise_()
        self.lblGs8c1.raise_()
        self.lblGs7c1.raise_()
        self.lblGs10c1.raise_()
        self.lblGs9c2.raise_()
        self.lblGs10c2.raise_()
        self.lblGs7c2.raise_()
        self.lblGs8c2.raise_()
        self.lblGs5c1.raise_()
        self.lblGs5c2.raise_()
        self.lblGs1c1.raise_()
        self.lblGs1c2.raise_()
        self.lblGs2c1.raise_()
        self.lblGs3c1.raise_()
        self.lblGs3c2.raise_()
        self.lblGs4c1.raise_()
        self.lblGs4c2.raise_()
        self.lblGpotsize.raise_()
        self.lblGc1.raise_()
        self.lblGc2.raise_()
        self.lblGc3.raise_()
        self.lblGc4.raise_()
        self.lblGc5.raise_()
        self.lblGs1a.raise_()
        self.lblGs1b.raise_()
        self.lblGs2b.raise_()
        self.lblGs3b.raise_()
        self.lblGs4b.raise_()
        self.lblGs5b.raise_()
        self.lblGs6b.raise_()
        self.lblGs7b.raise_()
        self.lblGs8b.raise_()
        self.lblGs9b.raise_()
        self.lblGs10b.raise_()
        self.lblGdealer.raise_()
        self.lblGs2c2.raise_()
        self.lblGs2a.raise_()
        self.lblGs3a.raise_()
        self.lblGs4a.raise_()
        self.lblGs5a.raise_()
        self.lblGs6a.raise_()
        self.lblGs7a.raise_()
        self.lblGs8a.raise_()
        self.lblGs9a.raise_()
        self.lblGs10a.raise_()
        self.tbRoomInfo = QtWidgets.QTextBrowser(self.tabGame)
        self.tbRoomInfo.setGeometry(QtCore.QRect(438, 533, 131, 102))
        self.tbRoomInfo.setObjectName("tbRoomInfo")
        self.lwChat = QtWidgets.QListWidget(self.tabGame)
        self.lwChat.setGeometry(QtCore.QRect(2, 533, 351, 80))
        self.lwChat.setAlternatingRowColors(True)
        self.lwChat.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lwChat.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lwChat.setWordWrap(True)
        self.lwChat.setObjectName("lwChat")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/joyemoji.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.lwChat.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwChat.addItem(item)
        self.leChatInput = QtWidgets.QLineEdit(self.tabGame)
        self.leChatInput.setGeometry(QtCore.QRect(2, 614, 97, 21))
        self.leChatInput.setText("")
        self.leChatInput.setObjectName("leChatInput")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabGame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(570, 530, 587, 127))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grlGbuttons = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grlGbuttons.setContentsMargins(0, 0, 0, 0)
        self.grlGbuttons.setHorizontalSpacing(0)
        self.grlGbuttons.setObjectName("grlGbuttons")
        self.slBetSize = QtWidgets.QSlider(self.gridLayoutWidget)
        self.slBetSize.setOrientation(QtCore.Qt.Horizontal)
        self.slBetSize.setObjectName("slBetSize")
        self.grlGbuttons.addWidget(self.slBetSize, 0, 2, 1, 1)
        self.sbBetSize = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sbBetSize.setObjectName("sbBetSize")
        self.grlGbuttons.addWidget(self.sbBetSize, 0, 3, 1, 1)
        self.velGbetbtns = QtWidgets.QHBoxLayout()
        self.velGbetbtns.setObjectName("velGbetbtns")
        self.velGfoldcheckbtns = QtWidgets.QVBoxLayout()
        self.velGfoldcheckbtns.setSpacing(0)
        self.velGfoldcheckbtns.setObjectName("velGfoldcheckbtns")
        self.btnFold = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFold.setObjectName("btnFold")
        self.velGfoldcheckbtns.addWidget(self.btnFold)
        self.btnCheck = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCheck.setObjectName("btnCheck")
        self.velGfoldcheckbtns.addWidget(self.btnCheck)
        self.velGbetbtns.addLayout(self.velGfoldcheckbtns)
        self.velGminhalfpotbtns = QtWidgets.QVBoxLayout()
        self.velGminhalfpotbtns.setSpacing(0)
        self.velGminhalfpotbtns.setObjectName("velGminhalfpotbtns")
        self.btnBetMin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBetMin.setObjectName("btnBetMin")
        self.velGminhalfpotbtns.addWidget(self.btnBetMin)
        self.btnBetHalfPot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBetHalfPot.setObjectName("btnBetHalfPot")
        self.velGminhalfpotbtns.addWidget(self.btnBetHalfPot)
        self.velGbetbtns.addLayout(self.velGminhalfpotbtns)
        self.velGallinpotbtns = QtWidgets.QVBoxLayout()
        self.velGallinpotbtns.setSpacing(0)
        self.velGallinpotbtns.setObjectName("velGallinpotbtns")
        self.btnBetPot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBetPot.setObjectName("btnBetPot")
        self.velGallinpotbtns.addWidget(self.btnBetPot)
        self.btnBetAllIn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBetAllIn.setObjectName("btnBetAllIn")
        self.velGallinpotbtns.addWidget(self.btnBetAllIn)
        self.velGbetbtns.addLayout(self.velGallinpotbtns)
        self.grlGbuttons.addLayout(self.velGbetbtns, 1, 2, 1, 1)
        self.velGcallbtns = QtWidgets.QVBoxLayout()
        self.velGcallbtns.setSpacing(0)
        self.velGcallbtns.setObjectName("velGcallbtns")
        self.btnCall = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCall.setObjectName("btnCall")
        self.velGcallbtns.addWidget(self.btnCall)
        self.cbCallAnyBet = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cbCallAnyBet.setObjectName("cbCallAnyBet")
        self.velGcallbtns.addWidget(self.cbCallAnyBet)
        self.grlGbuttons.addLayout(self.velGcallbtns, 1, 1, 1, 1)
        self.velGleavebtns = QtWidgets.QVBoxLayout()
        self.velGleavebtns.setSpacing(0)
        self.velGleavebtns.setObjectName("velGleavebtns")
        self.btnLeaveTable = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLeaveTable.setObjectName("btnLeaveTable")
        self.velGleavebtns.addWidget(self.btnLeaveTable)
        self.btnLeaveRoom = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnLeaveRoom.setObjectName("btnLeaveRoom")
        self.velGleavebtns.addWidget(self.btnLeaveRoom)
        self.grlGbuttons.addLayout(self.velGleavebtns, 0, 1, 1, 1)
        self.velGshowcardbtns = QtWidgets.QVBoxLayout()
        self.velGshowcardbtns.setSpacing(0)
        self.velGshowcardbtns.setObjectName("velGshowcardbtns")
        self.btnShowCard1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnShowCard1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 0, 0, 210), stop:1 rgba(255, 255, 255, 255))")
        self.btnShowCard1.setObjectName("btnShowCard1")
        self.velGshowcardbtns.addWidget(self.btnShowCard1)
        self.btnShowCard2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnShowCard2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 0, 0, 210), stop:1 rgba(255, 255, 255, 255))")
        self.btnShowCard2.setObjectName("btnShowCard2")
        self.velGshowcardbtns.addWidget(self.btnShowCard2)
        self.grlGbuttons.addLayout(self.velGshowcardbtns, 1, 0, 1, 1)
        self.btnBetRaise = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBetRaise.setObjectName("btnBetRaise")
        self.grlGbuttons.addWidget(self.btnBetRaise, 1, 3, 1, 1)
        self.holCardPreview = QtWidgets.QHBoxLayout()
        self.holCardPreview.setObjectName("holCardPreview")
        self.lblCardPreview1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCardPreview1.setMaximumSize(QtCore.QSize(35, 46))
        self.lblCardPreview1.setStyleSheet("font: 150 16pt;")
        self.lblCardPreview1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCardPreview1.setObjectName("lblCardPreview1")
        self.holCardPreview.addWidget(self.lblCardPreview1)
        self.lblCardPreview2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCardPreview2.setMaximumSize(QtCore.QSize(34, 46))
        self.lblCardPreview2.setStyleSheet("font: 150 16pt;")
        self.lblCardPreview2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCardPreview2.setObjectName("lblCardPreview2")
        self.holCardPreview.addWidget(self.lblCardPreview2)
        self.grlGbuttons.addLayout(self.holCardPreview, 0, 0, 1, 1)
        self.btnSendMessage = QtWidgets.QPushButton(self.tabGame)
        self.btnSendMessage.setGeometry(QtCore.QRect(99, 613, 50, 23))
        self.btnSendMessage.setObjectName("btnSendMessage")
        self.tabWidget = QtWidgets.QTabWidget(self.tabGame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 640, 284, 91))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab)
        self.listWidget_2.setAlternatingRowColors(True)
        self.listWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_4.addWidget(self.listWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tabwMain.addTab(self.tabGame, "")
        self.tabRooms = QtWidgets.QWidget()
        self.tabRooms.setObjectName("tabRooms")
        self.twRooms = QtWidgets.QTreeWidget(self.tabRooms)
        self.twRooms.setGeometry(QtCore.QRect(10, 140, 1061, 481))
        self.twRooms.setAlternatingRowColors(True)
        self.twRooms.setIndentation(0)
        self.twRooms.setAllColumnsShowFocus(True)
        self.twRooms.setColumnCount(4)
        self.twRooms.setObjectName("twRooms")
        item_0 = QtWidgets.QTreeWidgetItem(self.twRooms)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/password_lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon2)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(2, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.twRooms)
        item_0 = QtWidgets.QTreeWidgetItem(self.twRooms)
        item_0 = QtWidgets.QTreeWidgetItem(self.twRooms)
        item_0 = QtWidgets.QTreeWidgetItem(self.twRooms)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(2, brush)
        self.twRooms.header().setMinimumSectionSize(65)
        self.leJoinRoomPassword = QtWidgets.QLineEdit(self.tabRooms)
        self.leJoinRoomPassword.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.leJoinRoomPassword.setObjectName("leJoinRoomPassword")
        self.leJoinRoomName = QtWidgets.QLineEdit(self.tabRooms)
        self.leJoinRoomName.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.leJoinRoomName.setText("")
        self.leJoinRoomName.setObjectName("leJoinRoomName")
        self.btnJoinRoom = QtWidgets.QPushButton(self.tabRooms)
        self.btnJoinRoom.setGeometry(QtCore.QRect(14, 70, 141, 23))
        self.btnJoinRoom.setObjectName("btnJoinRoom")
        self.btnCreateRoom = QtWidgets.QPushButton(self.tabRooms)
        self.btnCreateRoom.setGeometry(QtCore.QRect(10, 100, 141, 23))
        self.btnCreateRoom.setObjectName("btnCreateRoom")
        self.leSearchRoom = QtWidgets.QLineEdit(self.tabRooms)
        self.leSearchRoom.setGeometry(QtCore.QRect(170, 10, 141, 20))
        self.leSearchRoom.setObjectName("leSearchRoom")
        self.lblRoomError = QtWidgets.QLabel(self.tabRooms)
        self.lblRoomError.setGeometry(QtCore.QRect(580, 10, 211, 16))
        self.lblRoomError.setObjectName("lblRoomError")
        self.cbHideProtectedRooms = QtWidgets.QCheckBox(self.tabRooms)
        self.cbHideProtectedRooms.setGeometry(QtCore.QRect(330, 30, 143, 16))
        self.cbHideProtectedRooms.setObjectName("cbHideProtectedRooms")
        self.cbHideEmptyRooms = QtWidgets.QCheckBox(self.tabRooms)
        self.cbHideEmptyRooms.setGeometry(QtCore.QRect(330, 50, 148, 17))
        self.cbHideEmptyRooms.setObjectName("cbHideEmptyRooms")
        self.cbHideFullRooms = QtWidgets.QCheckBox(self.tabRooms)
        self.cbHideFullRooms.setGeometry(QtCore.QRect(330, 70, 148, 17))
        self.cbHideFullRooms.setObjectName("cbHideFullRooms")
        self.btnRefreshRooms = QtWidgets.QPushButton(self.tabRooms)
        self.btnRefreshRooms.setGeometry(QtCore.QRect(230, 40, 75, 23))
        self.btnRefreshRooms.setObjectName("btnRefreshRooms")
        self.btnPrevRooms = QtWidgets.QPushButton(self.tabRooms)
        self.btnPrevRooms.setGeometry(QtCore.QRect(180, 100, 61, 23))
        self.btnPrevRooms.setObjectName("btnPrevRooms")
        self.lblRoomsPage = QtWidgets.QLabel(self.tabRooms)
        self.lblRoomsPage.setGeometry(QtCore.QRect(180, 70, 131, 16))
        self.lblRoomsPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRoomsPage.setObjectName("lblRoomsPage")
        self.btnNextRooms = QtWidgets.QPushButton(self.tabRooms)
        self.btnNextRooms.setGeometry(QtCore.QRect(250, 100, 61, 23))
        self.btnNextRooms.setObjectName("btnNextRooms")
        self.cbShowOnlyOfficialRooms = QtWidgets.QCheckBox(self.tabRooms)
        self.cbShowOnlyOfficialRooms.setGeometry(QtCore.QRect(330, 90, 131, 17))
        self.cbShowOnlyOfficialRooms.setObjectName("cbShowOnlyOfficialRooms")
        self.rbSortRoomsByName = QtWidgets.QRadioButton(self.tabRooms)
        self.rbSortRoomsByName.setGeometry(QtCore.QRect(500, 30, 82, 17))
        self.rbSortRoomsByName.setChecked(True)
        self.rbSortRoomsByName.setObjectName("rbSortRoomsByName")
        self.rbSortRoomsByPlayers = QtWidgets.QRadioButton(self.tabRooms)
        self.rbSortRoomsByPlayers.setGeometry(QtCore.QRect(500, 50, 82, 17))
        self.rbSortRoomsByPlayers.setObjectName("rbSortRoomsByPlayers")
        self.btnToggleRoomSorting = QtWidgets.QPushButton(self.tabRooms)
        self.btnToggleRoomSorting.setGeometry(QtCore.QRect(180, 40, 31, 23))
        self.btnToggleRoomSorting.setObjectName("btnToggleRoomSorting")
        self.lblRoomsFilter = QtWidgets.QLabel(self.tabRooms)
        self.lblRoomsFilter.setGeometry(QtCore.QRect(330, 10, 47, 13))
        self.lblRoomsFilter.setObjectName("lblRoomsFilter")
        self.lblRoomsSortBy = QtWidgets.QLabel(self.tabRooms)
        self.lblRoomsSortBy.setGeometry(QtCore.QRect(500, 10, 91, 16))
        self.lblRoomsSortBy.setObjectName("lblRoomsSortBy")
        self.comboBox = QtWidgets.QComboBox(self.tabRooms)
        self.comboBox.setGeometry(QtCore.QRect(500, 70, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../client/assets/protected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        self.pushButton = QtWidgets.QPushButton(self.tabRooms)
        self.pushButton.setGeometry(QtCore.QRect(330, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tabwMain.addTab(self.tabRooms, "")
        self.tabCommunity = QtWidgets.QWidget()
        self.tabCommunity.setObjectName("tabCommunity")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabCommunity)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.holCommunity = QtWidgets.QHBoxLayout()
        self.holCommunity.setObjectName("holCommunity")
        self.gbNews = QtWidgets.QGroupBox(self.tabCommunity)
        self.gbNews.setObjectName("gbNews")
        self.holCommunity.addWidget(self.gbNews)
        self.gbLookup = QtWidgets.QGroupBox(self.tabCommunity)
        self.gbLookup.setObjectName("gbLookup")
        self.leUserLookup = QtWidgets.QLineEdit(self.gbLookup)
        self.leUserLookup.setGeometry(QtCore.QRect(20, 20, 211, 20))
        self.leUserLookup.setObjectName("leUserLookup")
        self.btnUserLookup = QtWidgets.QPushButton(self.gbLookup)
        self.btnUserLookup.setGeometry(QtCore.QRect(250, 20, 75, 23))
        self.btnUserLookup.setObjectName("btnUserLookup")
        self.lwUserLookup = QtWidgets.QListWidget(self.gbLookup)
        self.lwUserLookup.setGeometry(QtCore.QRect(10, 50, 181, 291))
        self.lwUserLookup.setAlternatingRowColors(True)
        self.lwUserLookup.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.lwUserLookup.setObjectName("lwUserLookup")
        item = QtWidgets.QListWidgetItem()
        self.lwUserLookup.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwUserLookup.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwUserLookup.addItem(item)
        self.btnPrevUsersPage = QtWidgets.QPushButton(self.gbLookup)
        self.btnPrevUsersPage.setGeometry(QtCore.QRect(230, 90, 31, 23))
        self.btnPrevUsersPage.setObjectName("btnPrevUsersPage")
        self.lblUsersPage = QtWidgets.QLabel(self.gbLookup)
        self.lblUsersPage.setGeometry(QtCore.QRect(200, 60, 131, 20))
        self.lblUsersPage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUsersPage.setObjectName("lblUsersPage")
        self.btnNextUsersPage = QtWidgets.QPushButton(self.gbLookup)
        self.btnNextUsersPage.setGeometry(QtCore.QRect(270, 90, 31, 23))
        self.btnNextUsersPage.setObjectName("btnNextUsersPage")
        self.tbUserLookupStatus = QtWidgets.QTextBrowser(self.gbLookup)
        self.tbUserLookupStatus.setGeometry(QtCore.QRect(200, 200, 141, 141))
        self.tbUserLookupStatus.setObjectName("tbUserLookupStatus")
        self.lblUserLookupAvatar = QtWidgets.QLabel(self.gbLookup)
        self.lblUserLookupAvatar.setGeometry(QtCore.QRect(240, 130, 64, 64))
        self.lblUserLookupAvatar.setFrameShape(QtWidgets.QFrame.Box)
        self.lblUserLookupAvatar.setScaledContents(True)
        self.lblUserLookupAvatar.setObjectName("lblUserLookupAvatar")
        self.holCommunity.addWidget(self.gbLookup)
        self.gbProfile = QtWidgets.QGroupBox(self.tabCommunity)
        self.gbProfile.setObjectName("gbProfile")
        self.btnUserEditProfile = QtWidgets.QPushButton(self.gbProfile)
        self.btnUserEditProfile.setGeometry(QtCore.QRect(120, 30, 75, 23))
        self.btnUserEditProfile.setObjectName("btnUserEditProfile")
        self.lblUserProfileAvatar = QtWidgets.QLabel(self.gbProfile)
        self.lblUserProfileAvatar.setGeometry(QtCore.QRect(20, 30, 64, 64))
        self.lblUserProfileAvatar.setFrameShape(QtWidgets.QFrame.Box)
        self.lblUserProfileAvatar.setPixmap(QtGui.QPixmap("images/rubenpfp.png"))
        self.lblUserProfileAvatar.setScaledContents(True)
        self.lblUserProfileAvatar.setObjectName("lblUserProfileAvatar")
        self.tbUserProfileStatus = QtWidgets.QTextBrowser(self.gbProfile)
        self.tbUserProfileStatus.setGeometry(QtCore.QRect(20, 110, 171, 131))
        self.tbUserProfileStatus.setObjectName("tbUserProfileStatus")
        self.holCommunity.addWidget(self.gbProfile)
        self.gridLayout_2.addLayout(self.holCommunity, 0, 0, 1, 1)
        self.tabwMain.addTab(self.tabCommunity, "")
        self.tabLogIn = QtWidgets.QWidget()
        self.tabLogIn.setObjectName("tabLogIn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabLogIn)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grbLogIn = QtWidgets.QGroupBox(self.tabLogIn)
        self.grbLogIn.setObjectName("grbLogIn")
        self.formLayout = QtWidgets.QFormLayout(self.grbLogIn)
        self.formLayout.setObjectName("formLayout")
        self.lblLoginName = QtWidgets.QLabel(self.grbLogIn)
        self.lblLoginName.setObjectName("lblLoginName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblLoginName)
        self.leLoginName = QtWidgets.QLineEdit(self.grbLogIn)
        self.leLoginName.setMaxLength(16)
        self.leLoginName.setObjectName("leLoginName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leLoginName)
        self.lblLoginPassword = QtWidgets.QLabel(self.grbLogIn)
        self.lblLoginPassword.setObjectName("lblLoginPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblLoginPassword)
        self.leLoginPassword = QtWidgets.QLineEdit(self.grbLogIn)
        self.leLoginPassword.setMaxLength(64)
        self.leLoginPassword.setObjectName("leLoginPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leLoginPassword)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.cbLoginRememberMe = QtWidgets.QCheckBox(self.grbLogIn)
        self.cbLoginRememberMe.setObjectName("cbLoginRememberMe")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbLoginRememberMe)
        self.btnLogIn = QtWidgets.QPushButton(self.grbLogIn)
        self.btnLogIn.setObjectName("btnLogIn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnLogIn)
        self.btnLogInAsGuest = QtWidgets.QPushButton(self.grbLogIn)
        self.btnLogInAsGuest.setObjectName("btnLogInAsGuest")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.btnLogInAsGuest)
        self.lblLoginError = QtWidgets.QLabel(self.grbLogIn)
        self.lblLoginError.setObjectName("lblLoginError")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblLoginError)
        self.horizontalLayout.addWidget(self.grbLogIn)
        self.grbRegister = QtWidgets.QGroupBox(self.tabLogIn)
        self.grbRegister.setObjectName("grbRegister")
        self.formLayout_2 = QtWidgets.QFormLayout(self.grbRegister)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblRegisterName = QtWidgets.QLabel(self.grbRegister)
        self.lblRegisterName.setObjectName("lblRegisterName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblRegisterName)
        self.leRegisterName = QtWidgets.QLineEdit(self.grbRegister)
        self.leRegisterName.setMaxLength(16)
        self.leRegisterName.setObjectName("leRegisterName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leRegisterName)
        self.lblRegisterPassword = QtWidgets.QLabel(self.grbRegister)
        self.lblRegisterPassword.setObjectName("lblRegisterPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblRegisterPassword)
        self.leRegisterPassword = QtWidgets.QLineEdit(self.grbRegister)
        self.leRegisterPassword.setMaxLength(64)
        self.leRegisterPassword.setObjectName("leRegisterPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leRegisterPassword)
        self.lblRegisterRepeatPassword = QtWidgets.QLabel(self.grbRegister)
        self.lblRegisterRepeatPassword.setObjectName("lblRegisterRepeatPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblRegisterRepeatPassword)
        self.leRegisterRepeatPassword = QtWidgets.QLineEdit(self.grbRegister)
        self.leRegisterRepeatPassword.setMaxLength(64)
        self.leRegisterRepeatPassword.setObjectName("leRegisterRepeatPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leRegisterRepeatPassword)
        self.lblRegisterEmail = QtWidgets.QLabel(self.grbRegister)
        self.lblRegisterEmail.setObjectName("lblRegisterEmail")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblRegisterEmail)
        self.leRegisterEmail = QtWidgets.QLineEdit(self.grbRegister)
        self.leRegisterEmail.setMaxLength(64)
        self.leRegisterEmail.setObjectName("leRegisterEmail")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leRegisterEmail)
        self.cbRegisterWithoutEmail = QtWidgets.QCheckBox(self.grbRegister)
        self.cbRegisterWithoutEmail.setObjectName("cbRegisterWithoutEmail")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cbRegisterWithoutEmail)
        self.btnRegister = QtWidgets.QPushButton(self.grbRegister)
        self.btnRegister.setObjectName("btnRegister")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnRegister)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.lblRegisterError = QtWidgets.QLabel(self.grbRegister)
        self.lblRegisterError.setObjectName("lblRegisterError")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lblRegisterError)
        self.horizontalLayout.addWidget(self.grbRegister)
        self.tabwMain.addTab(self.tabLogIn, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabSettings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabwSettings = QtWidgets.QTabWidget(self.tabSettings)
        self.tabwSettings.setTabsClosable(False)
        self.tabwSettings.setObjectName("tabwSettings")
        self.tabSettingsGeneral = QtWidgets.QWidget()
        self.tabSettingsGeneral.setObjectName("tabSettingsGeneral")
        self.btnConnect = QtWidgets.QPushButton(self.tabSettingsGeneral)
        self.btnConnect.setGeometry(QtCore.QRect(240, 10, 75, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.btnDisconnect = QtWidgets.QPushButton(self.tabSettingsGeneral)
        self.btnDisconnect.setGeometry(QtCore.QRect(240, 50, 75, 23))
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.leConnectHostname = QtWidgets.QLineEdit(self.tabSettingsGeneral)
        self.leConnectHostname.setEnabled(False)
        self.leConnectHostname.setGeometry(QtCore.QRect(30, 10, 113, 22))
        self.leConnectHostname.setObjectName("leConnectHostname")
        self.sbConnectHostPort = QtWidgets.QSpinBox(self.tabSettingsGeneral)
        self.sbConnectHostPort.setEnabled(False)
        self.sbConnectHostPort.setGeometry(QtCore.QRect(160, 10, 61, 22))
        self.sbConnectHostPort.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbConnectHostPort.setMinimum(1)
        self.sbConnectHostPort.setMaximum(65535)
        self.sbConnectHostPort.setProperty("value", 2000)
        self.sbConnectHostPort.setObjectName("sbConnectHostPort")
        self.lblConnectColon = QtWidgets.QLabel(self.tabSettingsGeneral)
        self.lblConnectColon.setGeometry(QtCore.QRect(150, 10, 16, 16))
        self.lblConnectColon.setObjectName("lblConnectColon")
        self.tabwSettings.addTab(self.tabSettingsGeneral, "")
        self.tabSettingsAccount = QtWidgets.QWidget()
        self.tabSettingsAccount.setObjectName("tabSettingsAccount")
        self.grbCustomizeAccount = QtWidgets.QGroupBox(self.tabSettingsAccount)
        self.grbCustomizeAccount.setGeometry(QtCore.QRect(10, 10, 321, 341))
        self.grbCustomizeAccount.setObjectName("grbCustomizeAccount")
        self.lblChooseAvatarFile = QtWidgets.QLabel(self.grbCustomizeAccount)
        self.lblChooseAvatarFile.setGeometry(QtCore.QRect(10, 23, 101, 16))
        self.lblChooseAvatarFile.setObjectName("lblChooseAvatarFile")
        self.btnUploadAvatarFile = QtWidgets.QPushButton(self.grbCustomizeAccount)
        self.btnUploadAvatarFile.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.btnUploadAvatarFile.setObjectName("btnUploadAvatarFile")
        self.lbluploadDisclaimerAccount = QtWidgets.QLabel(self.grbCustomizeAccount)
        self.lbluploadDisclaimerAccount.setGeometry(QtCore.QRect(10, 160, 301, 16))
        self.lbluploadDisclaimerAccount.setObjectName("lbluploadDisclaimerAccount")
        self.label = QtWidgets.QLabel(self.grbCustomizeAccount)
        self.label.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.grbCustomizeAccount)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 110, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.grbCustomizeAccount)
        self.label_2.setGeometry(QtCore.QRect(60, 230, 64, 64))
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setLineWidth(3)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.grbCustomizeAccount)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 310, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.grbCustomizeAccount)
        self.label_3.setGeometry(QtCore.QRect(150, 230, 64, 64))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setLineWidth(3)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../default_user_files/avatar.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.tabwSettings.addTab(self.tabSettingsAccount, "")
        self.tabSettingsChat = QtWidgets.QWidget()
        self.tabSettingsChat.setObjectName("tabSettingsChat")
        self.tabwSettings.addTab(self.tabSettingsChat, "")
        self.tabSettingsAudio = QtWidgets.QWidget()
        self.tabSettingsAudio.setObjectName("tabSettingsAudio")
        self.tabwSettings.addTab(self.tabSettingsAudio, "")
        self.tabSettingsGame = QtWidgets.QWidget()
        self.tabSettingsGame.setObjectName("tabSettingsGame")
        self.grbCustomizeGame = QtWidgets.QGroupBox(self.tabSettingsGame)
        self.grbCustomizeGame.setGeometry(QtCore.QRect(20, 10, 351, 221))
        self.grbCustomizeGame.setObjectName("grbCustomizeGame")
        self.lblChooseBackgroundFile = QtWidgets.QLabel(self.grbCustomizeGame)
        self.lblChooseBackgroundFile.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.lblChooseBackgroundFile.setObjectName("lblChooseBackgroundFile")
        self.btnUploadBackgroundFile = QtWidgets.QPushButton(self.grbCustomizeGame)
        self.btnUploadBackgroundFile.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.btnUploadBackgroundFile.setObjectName("btnUploadBackgroundFile")
        self.lblChooseTableFile = QtWidgets.QLabel(self.grbCustomizeGame)
        self.lblChooseTableFile.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.lblChooseTableFile.setObjectName("lblChooseTableFile")
        self.btnUploadTableFile = QtWidgets.QPushButton(self.grbCustomizeGame)
        self.btnUploadTableFile.setGeometry(QtCore.QRect(10, 90, 75, 23))
        self.btnUploadTableFile.setObjectName("btnUploadTableFile")
        self.lblChooseCardDeckFolder = QtWidgets.QLabel(self.grbCustomizeGame)
        self.lblChooseCardDeckFolder.setGeometry(QtCore.QRect(10, 120, 141, 21))
        self.lblChooseCardDeckFolder.setObjectName("lblChooseCardDeckFolder")
        self.btnUploadDeckDirectory = QtWidgets.QPushButton(self.grbCustomizeGame)
        self.btnUploadDeckDirectory.setGeometry(QtCore.QRect(10, 140, 111, 23))
        self.btnUploadDeckDirectory.setObjectName("btnUploadDeckDirectory")
        self.lblUploadDisclaimerGame = QtWidgets.QLabel(self.grbCustomizeGame)
        self.lblUploadDisclaimerGame.setGeometry(QtCore.QRect(10, 180, 301, 16))
        self.lblUploadDisclaimerGame.setObjectName("lblUploadDisclaimerGame")
        self.tabwSettings.addTab(self.tabSettingsGame, "")
        self.tabSettingsRoom = QtWidgets.QWidget()
        self.tabSettingsRoom.setObjectName("tabSettingsRoom")
        self.tabwSettings.addTab(self.tabSettingsRoom, "")
        self.gridLayout_5.addWidget(self.tabwSettings, 0, 0, 1, 1)
        self.tabwMain.addTab(self.tabSettings, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.lblCredits = QtWidgets.QLabel(self.tabAbout)
        self.lblCredits.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.lblCredits.setObjectName("lblCredits")
        self.listWidget = QtWidgets.QListWidget(self.tabAbout)
        self.listWidget.setGeometry(QtCore.QRect(10, 100, 481, 111))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lblUiVersion = QtWidgets.QLabel(self.tabAbout)
        self.lblUiVersion.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.lblUiVersion.setObjectName("lblUiVersion")
        self.tabwMain.addTab(self.tabAbout, "")
        self.gridLayout.addWidget(self.tabwMain, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.MainWidget)

        self.retranslateUi(MainWindow)
        self.tabwMain.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        self.tabwSettings.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Shove"))
        self.lblGpotsize.setText(_translate("MainWindow", "Pot: 99999999999"))
        self.lblGs1b.setText(_translate("MainWindow", "42042042042042"))
        self.lblGs2b.setText(_translate("MainWindow", "5"))
        self.lblGs3b.setText(_translate("MainWindow", "5"))
        self.lblGs4b.setText(_translate("MainWindow", "5"))
        self.lblGs5b.setText(_translate("MainWindow", "5"))
        self.lblGs6b.setText(_translate("MainWindow", "5"))
        self.lblGs7b.setText(_translate("MainWindow", "5"))
        self.lblGs8b.setText(_translate("MainWindow", "5"))
        self.lblGs9b.setText(_translate("MainWindow", "5"))
        self.lblGs10b.setText(_translate("MainWindow", "5"))
        self.tbRoomInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Room: 2e Kamer ft. FvD</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Players: 100</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Description: x</span></p></body></html>"))
        __sortingEnabled = self.lwChat.isSortingEnabled()
        self.lwChat.setSortingEnabled(False)
        item = self.lwChat.item(0)
        item.setText(_translate("MainWindow", "[sticker]?"))
        item = self.lwChat.item(1)
        item.setText(_translate("MainWindow", "😂"))
        self.lwChat.setSortingEnabled(__sortingEnabled)
        self.leChatInput.setPlaceholderText(_translate("MainWindow", "Type here..."))
        self.btnFold.setText(_translate("MainWindow", "Fold"))
        self.btnCheck.setText(_translate("MainWindow", "Check"))
        self.btnBetMin.setText(_translate("MainWindow", "Min."))
        self.btnBetHalfPot.setText(_translate("MainWindow", "1/2 Pot"))
        self.btnBetPot.setText(_translate("MainWindow", "Pot"))
        self.btnBetAllIn.setText(_translate("MainWindow", "All in"))
        self.btnCall.setText(_translate("MainWindow", "Call"))
        self.cbCallAnyBet.setText(_translate("MainWindow", "Call any bet"))
        self.btnLeaveTable.setText(_translate("MainWindow", "Leave table"))
        self.btnLeaveRoom.setText(_translate("MainWindow", "Leave room"))
        self.btnShowCard1.setText(_translate("MainWindow", "Show Card 1"))
        self.btnShowCard2.setText(_translate("MainWindow", "Show Card 2"))
        self.btnBetRaise.setText(_translate("MainWindow", "Raise (x)"))
        self.lblCardPreview1.setText(_translate("MainWindow", "2c"))
        self.lblCardPreview2.setText(_translate("MainWindow", "Jc"))
        self.btnSendMessage.setText(_translate("MainWindow", "Send"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "NEW"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "yee"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "CHAT"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Global"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Room"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "@comrade"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabGame), _translate("MainWindow", "Game"))
        self.twRooms.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.twRooms.headerItem().setText(1, _translate("MainWindow", "Description"))
        self.twRooms.headerItem().setText(2, _translate("MainWindow", "Players"))
        self.twRooms.headerItem().setText(3, _translate("MainWindow", "Country"))
        __sortingEnabled = self.twRooms.isSortingEnabled()
        self.twRooms.setSortingEnabled(False)
        self.twRooms.topLevelItem(0).setText(0, _translate("MainWindow", "TRUMP_GANG"))
        self.twRooms.topLevelItem(0).setText(1, _translate("MainWindow", "maga"))
        self.twRooms.topLevelItem(0).setText(2, _translate("MainWindow", "10/10"))
        self.twRooms.topLevelItem(0).setText(3, _translate("MainWindow", "US"))
        self.twRooms.topLevelItem(1).setText(0, _translate("MainWindow", "234234"))
        self.twRooms.topLevelItem(2).setText(0, _translate("MainWindow", "234"))
        self.twRooms.topLevelItem(3).setText(0, _translate("MainWindow", "1"))
        self.twRooms.topLevelItem(4).setText(0, _translate("MainWindow", "1"))
        self.twRooms.topLevelItem(4).setText(1, _translate("MainWindow", "Official room 1"))
        self.twRooms.topLevelItem(4).setText(2, _translate("MainWindow", "5/10"))
        self.twRooms.topLevelItem(4).setText(3, _translate("MainWindow", "NL"))
        self.twRooms.setSortingEnabled(__sortingEnabled)
        self.leJoinRoomPassword.setPlaceholderText(_translate("MainWindow", "Room password..."))
        self.leJoinRoomName.setPlaceholderText(_translate("MainWindow", "Room name..."))
        self.btnJoinRoom.setText(_translate("MainWindow", "Join room"))
        self.btnCreateRoom.setText(_translate("MainWindow", "Create room"))
        self.leSearchRoom.setPlaceholderText(_translate("MainWindow", "Search room..."))
        self.lblRoomError.setText(_translate("MainWindow", "Error"))
        self.cbHideProtectedRooms.setText(_translate("MainWindow", "Hide password protected"))
        self.cbHideEmptyRooms.setText(_translate("MainWindow", "Hide empty"))
        self.cbHideFullRooms.setText(_translate("MainWindow", "Hide full"))
        self.btnRefreshRooms.setText(_translate("MainWindow", "Refresh"))
        self.btnPrevRooms.setText(_translate("MainWindow", "<"))
        self.lblRoomsPage.setText(_translate("MainWindow", "Page"))
        self.btnNextRooms.setText(_translate("MainWindow", ">"))
        self.cbShowOnlyOfficialRooms.setText(_translate("MainWindow", "Show only official"))
        self.rbSortRoomsByName.setText(_translate("MainWindow", "Name"))
        self.rbSortRoomsByPlayers.setText(_translate("MainWindow", "Players"))
        self.btnToggleRoomSorting.setText(_translate("MainWindow", "\\/"))
        self.lblRoomsFilter.setText(_translate("MainWindow", "Filter:"))
        self.lblRoomsSortBy.setText(_translate("MainWindow", "Sort by:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ok"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ok2"))
        self.pushButton.setText(_translate("MainWindow", "ok"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabRooms), _translate("MainWindow", "Rooms"))
        self.gbNews.setTitle(_translate("MainWindow", "News"))
        self.gbLookup.setTitle(_translate("MainWindow", "Lookup user"))
        self.leUserLookup.setPlaceholderText(_translate("MainWindow", "Lookup user..."))
        self.btnUserLookup.setText(_translate("MainWindow", "Lookup"))
        self.lwUserLookup.setSortingEnabled(True)
        __sortingEnabled = self.lwUserLookup.isSortingEnabled()
        self.lwUserLookup.setSortingEnabled(False)
        item = self.lwUserLookup.item(0)
        item.setText(_translate("MainWindow", "adf"))
        item = self.lwUserLookup.item(1)
        item.setText(_translate("MainWindow", "dfgsdfgsdfg"))
        item = self.lwUserLookup.item(2)
        item.setText(_translate("MainWindow", "sdfgsdfg"))
        self.lwUserLookup.setSortingEnabled(__sortingEnabled)
        self.btnPrevUsersPage.setText(_translate("MainWindow", "<"))
        self.lblUsersPage.setText(_translate("MainWindow", "Page"))
        self.btnNextUsersPage.setText(_translate("MainWindow", ">"))
        self.lblUserLookupAvatar.setText(_translate("MainWindow", "avatar"))
        self.gbProfile.setTitle(_translate("MainWindow", "Profile"))
        self.btnUserEditProfile.setText(_translate("MainWindow", "Edit profile"))
        self.lblUserProfileAvatar.setText(_translate("MainWindow", "avatar"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabCommunity), _translate("MainWindow", "Community"))
        self.grbLogIn.setTitle(_translate("MainWindow", "Log in"))
        self.lblLoginName.setText(_translate("MainWindow", "<html><head/><body><p>Name:</p></body></html>"))
        self.lblLoginPassword.setText(_translate("MainWindow", "Password:"))
        self.cbLoginRememberMe.setText(_translate("MainWindow", "Remember me"))
        self.btnLogIn.setText(_translate("MainWindow", "Log in"))
        self.btnLogInAsGuest.setText(_translate("MainWindow", "Log in as guest"))
        self.lblLoginError.setText(_translate("MainWindow", "Error"))
        self.grbRegister.setTitle(_translate("MainWindow", "Register"))
        self.lblRegisterName.setText(_translate("MainWindow", "Name:"))
        self.lblRegisterPassword.setText(_translate("MainWindow", "Password:"))
        self.lblRegisterRepeatPassword.setText(_translate("MainWindow", "Repeat password:"))
        self.lblRegisterEmail.setText(_translate("MainWindow", "E-mail:"))
        self.cbRegisterWithoutEmail.setText(_translate("MainWindow", "Register without e-mail"))
        self.btnRegister.setText(_translate("MainWindow", "Register"))
        self.lblRegisterError.setText(_translate("MainWindow", "Error"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabLogIn), _translate("MainWindow", "Log in"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.btnDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.leConnectHostname.setText(_translate("MainWindow", "localhost"))
        self.leConnectHostname.setPlaceholderText(_translate("MainWindow", "Hostname"))
        self.lblConnectColon.setText(_translate("MainWindow", ":"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsGeneral), _translate("MainWindow", "General"))
        self.grbCustomizeAccount.setTitle(_translate("MainWindow", "Customize account"))
        self.lblChooseAvatarFile.setText(_translate("MainWindow", "Choose avatar:"))
        self.btnUploadAvatarFile.setText(_translate("MainWindow", "Upload file"))
        self.lbluploadDisclaimerAccount.setText(_translate("MainWindow", "Selected file is uploaded upon selecting"))
        self.label.setText(_translate("MainWindow", "Choose border:"))
        self.pushButton_2.setText(_translate("MainWindow", "Upload file"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsAccount), _translate("MainWindow", "Account"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsChat), _translate("MainWindow", "Chat"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsAudio), _translate("MainWindow", "Audio"))
        self.grbCustomizeGame.setTitle(_translate("MainWindow", "Customize game"))
        self.lblChooseBackgroundFile.setText(_translate("MainWindow", "Choose background:"))
        self.btnUploadBackgroundFile.setText(_translate("MainWindow", "Upload file"))
        self.lblChooseTableFile.setText(_translate("MainWindow", "Choose table:"))
        self.btnUploadTableFile.setText(_translate("MainWindow", "Upload file"))
        self.lblChooseCardDeckFolder.setText(_translate("MainWindow", "Choose deck directory:"))
        self.btnUploadDeckDirectory.setText(_translate("MainWindow", "Upload directory"))
        self.lblUploadDisclaimerGame.setText(_translate("MainWindow", "Selected file/directory is uploaded upon selecting"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsGame), _translate("MainWindow", "Game"))
        self.tabwSettings.setTabText(self.tabwSettings.indexOf(self.tabSettingsRoom), _translate("MainWindow", "Room"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabSettings), _translate("MainWindow", "Settings"))
        self.lblCredits.setText(_translate("MainWindow", "Credits"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Icons made by Freepik from www.flaticon.com, licensed by CC 3.0"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "<add most assets here>"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Default background stolen from Microsoft"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lblUiVersion.setText(_translate("MainWindow", "1.0"))
        self.tabwMain.setTabText(self.tabwMain.indexOf(self.tabAbout), _translate("MainWindow", "About"))

